export const address_list = [
    {
        district: 'Quận Cẩm Lệ',
        wards: [
            'phường Hòa An',
            'phường Hòa Thọ Đông',
            'phường Hòa Xuân',
            'phường Hòa Phát',
            'phường Hòa Thọ Tây',
            'phường Khuê Trung',
        ],
        streets: [
            'đường 29 tháng 3',
            'đường Bắc Sơn',
            'đường Bãi Sậy',
            'đường Bàu Trâm Trung',
            'đường Bích Khê',
            'đường Bùi Công Trừng',
            'đường Bùi Giáng',
            'đường Bùi Hiển',
            'đường Bùi Kỷ',
            'đường Bùi Tấn Diên',
            'đường Bùi Thiện Ngộ',
            'đường Bùi Trang Chước',
            'đường Bùi Vịnh',
            'đường Bùi Xương Trạch',
            'đường Bùi Xương Tự',
            'đường Cách Mạng Tháng Tám',
            'đường Cao Sơn Pháo',
            'đường Cao Xuân Huy',
            'đường Chế Viết Tấn',
            'đường Chu Mạnh Trinh',
            'đường Cống Quỳnh',
            'đường Đàm Văn Lễ',
            'đường Đặng Đức Siêu',
            'đường Đặng Hòa',
            'đường Đặng Nhơn',
            'đường Đặng Như Mai',
            'đường Đặng Văn Ngữ',
            'đường Đặng Xuân Bảng',
            'đường Đào Công Chính',
            'đường Đậu Quang Lĩnh',
            'đường Diên Hồng',
            'đường Diệp Minh Châu',
            'đường Đinh Châu',
            'đường Đinh Gia Trinh',
            'đường Đinh Liệt',
            'đường Đinh Nhật Tân',
            'đường Đinh Văn Chấp',
            'đường Đỗ Đăng Đệ',
            'đường Đỗ Đăng Tuyển',
            'đường Đô Đốc Bảo',
            'đường Đô Đốc Lân',
            'đường Đô Đốc Lộc',
            'đường Đô Đốc Tuyết',
            'đường Đỗ Đức Dục',
            'đường Đỗ Quỳ',
            'đường Đỗ Thúc Tịnh',
            'đường Đỗ Tự',
            'đường Đội Cấn',
            'đường Đội Cung',
            'đường Đoàn Hữu Trưng',
            'đường Đoàn Ngọc Nhạc',
            'đường Đoàn Nguyễn Thục',
            'đường Đoàn Nguyễn Tuấn',
            'đường Đoàn Quý Phi',
            'đường Đống Công Tường',
            'đường Dương Bá Cung',
            'đường Dương Đức Nhan',
            'đường Dương Loan',
            'đường Dương Quảng Hàm',
            'đường Hà Bồng',
            'đường Hà Duy Phiên',
            'đường Hà Mục',
            'đường Hà Tông Quyền',
            'đường Hà Văn Trí',
            'đường Hàn Thuyên',
            'đường Hồ Biểu Chánh',
            'đường Hồ Đắc Di',
            'đường Hồ Nguyên Trừng',
            'đường Hồ Phi Tích',
            'đường Hồ Sĩ Dương',
            'đường Hồ Trung Lượng',
            'đường Hồ Tỵ',
            'đường Hoàng Châu Ký',
            'đường Hoàng Đạo Thành',
            'đường Hoàng Đạo Thúy',
            'đường Hoàng Đình Ái',
            'đường Hoàng Dư Khương',
            'đường Hoàng Hiệp',
            'đường Hoàng Minh Giám',
            'đường Hoàng Ngọc Phách',
            'đường Hoàng Sâm',
            'đường Hoàng Tăng Bí',
            'đường Hoàng Thế Thiện',
            'đường Hoàng Thị Ái',
            'đường Hoàng Xuân Hãn',
            'đường Hoàng Xuân Nhị',
            'đường Huy Cận',
            'đường Huỳnh Ngọc Đủ',
            'đường Huỳnh Tấn Phát',
            'đường Huỳnh Tịnh Của',
            'đường Huỳnh Văn Đảnh',
            'đường Huỳnh Văn Gấm',
            'đường Khương Hữu Dụng',
            'đường Kiều Phụng',
            'đường Kiều Sơn Đen',
            'đường La Hối',
            'đường Lâm Nhĩ',
            'đường Lê Ấm',
            'đường Lê Cao Lãng',
            'đường Lê Đại Hành',
            'đường Lê Đỉnh',
            'đường Lê Đình Kỵ',
            'đường Lê Duy Lương',
            'đường Lê Hiến Mai',
            'đường Lê Hồng Sơn',
            'đường Lê Kim Lăng',
            'đường Lê Minh Trung',
            'đường Lê Ngân',
            'đường Lê Nổ',
            'đường Lê Quảng Chí',
            'đường Lê Quang Định',
            'đường Lê Quang Hòa',
            'đường Lê Sỹ',
            'đường Lê Thạch',
            'đường Lê Thận',
            'đường Lê Thanh Nghị',
            'đường Lê Thiết Hùng',
            'đường Lê Trọng Tấn',
            'đường Lê Văn An',
            'đường Lê Văn Đức',
            'đường Lê Văn Linh',
            'đường Lê Vĩnh Khanh',
            'đường Lư Giang',
            'đường Lương Định Của',
            'đường Lương Khắc Ninh',
            'đường Lương Nhữ Hộc',
            'đường Lương Văn Can',
            'đường Lưu Nhân Chú',
            'đường Lý Nhân Tông',
            'đường Lý Tế Xuyên',
            'đường Mạc Đăng Doanh',
            'đường Mạc Đăng Dung',
            'đường Mạc Thị Bưởi',
            'đường Mai Anh Tuấn',
            'đường Mai Chí Thọ',
            'đường Mẹ Thứ',
            'đường Nam Trân',
            'đường Ngô Huy Diễn',
            'đường Ngô Mây',
            'đường Ngô Nhân Tịnh',
            'đường Ngô Thế Lân',
            'đường Nguyễn Ân',
            'đường Nguyễn Bính',
            'đường Nguyễn Công Hoan',
            'đường Nguyễn Công Triều',
            'đường Nguyễn Cư Trinh',
            'đường Nguyễn Đăng Đạo',
            'đường Nguyễn Đình Thi',
            'đường Nguyễn Đình Tứ',
            'đường Nguyễn Đỗ Mục',
            'đường Nguyễn Đóa',
            'đường Nguyễn Đổng Chi',
            'đường Nguyễn Dữ',
            'đường Nguyễn Đức Thiệu',
            'đường Nguyễn Duy',
            'đường Nguyễn Hàng',
            'đường Nguyễn Hiến Lê',
            'đường Nguyễn Hữu Thọ',
            'đường Nguyễn Hữu Tiến',
            'đường Nguyễn Huy Tưởng',
            'đường Nguyễn Khánh Toàn',
            'đường Nguyễn Khoa Chiêm',
            'đường Nguyễn Kim',
            'đường Nguyễn Lai',
            'đường Nguyễn Lý',
            'đường Nguyễn Mậu Tài',
            'đường Nguyễn Mỹ',
            'đường Nguyễn Nhàn',
            'đường Nguyễn Nho Túy',
            'đường Nguyễn Như Đãi',
            'đường Nguyễn Như Đổ',
            'đường Nguyễn Phẩm',
            'đường Nguyễn Phong Sắc',
            'đường Nguyễn Phú Hường',
            'đường Nguyễn Phước Lan',
            'đường Nguyễn Phước Tần',
            'đường Nguyễn Quang Chung',
            'đường Nguyễn Quang Diêu',
            'đường Nguyễn Quang Lâm',
            'đường Nguyễn Quý Đức',
            'đường Nguyễn Quyền',
            'đường Nguyễn Sắc Kim',
            'đường Nguyễn Thế Lịch',
            'đường Nguyễn Thị Sáu',
            'đường Nguyễn Thuật',
            'đường Nguyễn Thượng Hiền',
            'đường Nguyễn Trác',
            'đường Nguyễn Trung Ngạn',
            'đường Nguyễn Văn Bổng',
            'đường Nguyễn Văn Giáp',
            'đường Nguyễn Văn Huyên',
            'đường Nguyễn Văn Ngọc',
            'đường Nguyễn Văn Tấn',
            'đường Nguyễn Văn Tạo',
            'đường Nguyễn Văn Thông',
            'đường Nguyễn Văn Xuân',
            'đường Nguyễn Xuân',
            'đường Nguyễn Xuân Hữu',
            'đường Nguyễn Xuân Lâm',
            'đường Nhất Chí Mai',
            'đường Nhơn Hòa Xuân',
            'đường Nơ Trang Lơng',
            'đường Núi Thành',
            'đường Ông Ích Đường',
            'đường Phạm Bành',
            'đường Phạm Duy Tốn',
            'đường Phạm Hùng',
            'đường Phạm Hữu Nghi',
            'đường Phạm Phú Tiết',
            'đường Phạm Sư Mạnh',
            'đường Phạm Thế Hiển',
            'đường Phạm Tứ',
            'đường Phạm Viết Chánh',
            'đường Phạm Vinh',
            'đường Phạm Xuân Ẩn',
            'đường Phan Anh',
            'đường Phan Đăng Lưu',
            'đường Phan Khoang',
            'đường Phan Khôi',
            'đường Phan Ngọc Nhân',
            'đường Phan Sĩ Thực',
            'đường Phan Thao',
            'đường Phan Triêm',
            'đường Phan Trọng Tuệ',
            'đường Phan Văn Đáng',
            'đường Phan Văn Trị',
            'đường Phù Đổng',
            'đường Quách Thị Trang',
            'đường Quách Xân',
            'đường Tế Hanh',
            'đường Thái Văn Lung',
            'đường Thân Cảnh Phúc',
            'đường Thân Công Tài',
            'đường Thăng Long',
            'đường Thanh Hóa',
            'đường Thành Thái',
            'đường Thiều Chửu',
            'đường Thu Bồn',
            'đường Tố Hữu',
            'đường Tô Vĩnh Diện',
            'đường Tôn Đản',
            'đường Tôn Đức Thắng',
            'đường Tôn Thất Dương Kỵ',
            'đường Tôn Thất Thuyết',
            'đường Trần Đình Long',
            'đường Trần Đình Nam',
            'đường Trần Đình Phong',
            'đường Trần Đức Thảo',
            'đường Trần Huấn',
            'đường Trần Hữu Duẩn',
            'đường Trần Huy Liệu',
            'đường Trần Kim Bảng',
            'đường Trần Kim Xuyến',
            'đường Trần Lê',
            'đường Trần Lựu',
            'đường Trần Mai Ninh',
            'đường Trần Nam Trung',
            'đường Trần Ngọc Sương',
            'đường Trần Phước Thành',
            'đường Trần Quốc Thảo',
            'đường Trần Quý Hai',
            'đường Trần Thủ Độ',
            'đường Trần Thúc Nhẫn',
            'đường Trần Văn Đang',
            'đường Trần Văn Giáp',
            'đường Trần Văn Lan',
            'đường Trần Văn Trà',
            'đường Trần Văn Ơn',
            'đường Trần Viện',
            'đường Trần Xuân Soạn',
            'đường Triệu Quốc Đạt',
            'đường Trịnh Đình Thảo',
            'đường Trinh Đường',
            'đường Trịnh Hoài Đức',
            'đường Trịnh Khả',
            'đường Trừ Văn Thố',
            'đường Trường Chinh',
            'đường Trương Minh Ký',
            'đường Trương Quang Giao',
            'đường Trường Sơn',
            'đường Tú Mỡ',
            'đường Văn Tiến Dũng',
            'đường Võ An Ninh',
            'đường Võ Chí Công',
            'đường Võ Quảng',
            'đường Võ Sạ',
            'đường Võ Thành Vỹ',
            'đường Võ Văn Ngân',
            'đường Vũ Cán',
            'đường Vũ Đình Liên',
            'đường Vũ Hàn',
            'đường Vũ Lăng',
            'đường Vũ Thạnh',
            'đường Vũ Thành Năm',
            'đường Vũ Trọng Hoàng',
            'đường Vũ Xuân Thiều',
            'đường Xô Viết Nghệ Tĩnh',
            'đường Xuân Thủy',
            'đường Yên Thế',
        ],
    },
    {
        district: 'Quận Hải Châu',
        wards: [
            'phường Bình Hiên',
            'phường Bình Thuận',
            'phường Hải Châu I',
            'phường Hải Châu II',
            'phường Hòa Cường Bắc',
            'phường Hòa Cường Nam',
            'phường Hòa Thuận Đông',
            'phường Hòa Thuận Tây',
            'phường Nam Dương',
            'phường Phước Ninh',
            'phường Thạch Thang',
            'phường Thanh Bình',
            'phường Thuận Phước',
        ],
        streets: [
            'đường 3 tháng 2',
            'đường 30 tháng 4',
            'đường 2 tháng 9',
            'đường Ba Đình',
            'đường Bắc Đẩu',
            'đường Bạch Đằng',
            'đường Bùi Kỷ',
            'đường Bùi Sĩ Tiêm',
            'đường Bùi Viện',
            'đường Bùi Xuân Phái',
            'đường Ca Văn Thỉnh',
            'đường Cầm Bá Thước',
            'đường Cao Thắng',
            'đường Cao Xuân Dục',
            'đường Cao Xuân Huy',
            'đường Châu Thượng Văn',
            'đường Châu Văn Liêm',
            'đường Chi Lăng',
            'đường Chu Mạnh Trinh',
            'đường Chu Văn An',
            'đường Cô Bắc',
            'đường Cô Giang',
            'đường Đặng Nguyên Cẩn',
            'đường Đặng Thùy Trâm',
            'đường Đặng Tử Kính',
            'đường Đào Cam Mộc',
            'đường Đào Tấn',
            'đường Đinh Công Tráng',
            'đường Đinh Tiên Hoàng',
            'đường Đỗ Pháp Thuận',
            'đường Đỗ Xuân Cát',
            'đường Doãn Khuê',
            'đường Đoàn Quý Phi',
            'đường Đoàn Thị Điểm',
            'đường Đốc Ngữ',
            'đường Đống Đa',
            'đường Đức Lợi',
            'đường Dương Bá Trạc',
            'đường Dương Quảng Hàm',
            'đường Dương Thưởng',
            'đường Duy Tân',
            'đường Giang Văn Minh',
            'đường Hà Huy Giáp',
            'đường Hải Hồ',
            'đường Hải Phòng',
            'đường Hải Sơn',
            'đường Hàn Mặc Tử',
            'đường Hàn Thuyên',
            'đường Hồ Biểu Chánh',
            'đường Hồ Nguyên Trừng',
            'đường Hồ Tông Thốc',
            'đường Hoàng Diệu',
            'đường Hoàng Thúc Trâm',
            'đường Hoàng Tích Trí',
            'đường Hoàng Văn Thụ',
            'đường Hoàng Xuân Nhị',
            'đường Hùng Vương',
            'đường Huy Cận',
            'đường Huỳnh Lý',
            'đường Huỳnh Mẫn Đạt',
            'đường Huỳnh Ngọc Huệ',
            'đường Huỳnh Tấn Phát',
            'đường Huỳnh Thúc Kháng',
            'đường Lê Anh Xuân',
            'đường Lê Bá Trinh',
            'đường Lê Cơ',
            'đường Lê Đại',
            'đường Lê Đình Dương',
            'đường Lê Đình Lý',
            'đường Lê Đình Thám',
            'đường Lê Duẩn',
            'đường Lê Duy Lương',
            'đường Lê Hồng Phong',
            'đường Lê Khắc Cần',
            'đường Lê Khôi',
            'đường Lê Lai',
            'đường Lê Lợi',
            'đường Lê Nỗ',
            'đường Lê Quý Đôn',
            'đường Lê Sát',
            'đường Lê Thanh Nghị',
            'đường Lê Thánh Tôn',
            'đường Lê Thị Hồng Gấm',
            'đường Lê Văn Đức',
            'đường Lê Văn Long',
            'đường Lê Vĩnh Huy',
            'đường Lương Ngọc Quyến',
            'đường Lương Nhữ Hộc',
            'đường Lưu Quý Kỳ',
            'đường Lưu Trọng Lư',
            'đường Lý Nhân Tông',
            'đường Lý Thường Kiệt',
            'đường Lý Tự Trọng',
            'đường Mạc Đĩnh Chi',
            'đường Mạc Thị Bưởi',
            'đường Mai Am',
            'đường Mai Dị',
            'đường Mai Lão Bạng',
            'đường Man Thiện',
            'đường Nại Nam',
            'đường Ngô Chi Lan',
            'đường Ngô Gia Tự',
            'đường Ngô Tất Tố',
            'đường Ngô Thế Vinh',
            'đường Ngô Thị Liễu',
            'đường Nguyễn Bá Học',
            'đường Nguyễn Bình',
            'đường Nguyễn Chí Thanh',
            'đường Nguyễn Cư Trinh',
            'đường Nguyễn Đôn Tiết',
            'đường Nguyễn Đổng Chi',
            'đường Nguyễn Du',
            'đường Nguyễn Dữ',
            'đường Nguyễn Đức Cảnh',
            'đường Nguyễn Hanh',
            'đường Nguyễn Hoàng',
            'đường Nguyễn Hữu Cảnh',
            'đường Nguyễn Hữu Dật',
            'đường Nguyễn Hữu Thọ',
            'đường Nguyễn Khánh Toàn',
            'đường Nguyễn Khoái',
            'đường Nguyễn Lộ Trạch',
            'đường Nguyễn Phẩm',
            'đường Nguyễn Quang Bích',
            'đường Nguyễn Sơn',
            'đường Nguyễn Sơn Hà',
            'đường Nguyễn Súy',
            'đường Nguyễn Tất Thành',
            'đường Nguyễn Thái Học',
            'đường Nguyễn Thành Hãn',
            'đường Nguyễn Thành Ý',
            'đường Nguyễn Thi',
            'đường Nguyễn Thị Minh Khai',
            'đường Nguyễn Thiện Thuật',
            'đường Nguyễn Trác',
            'đường Nguyễn Trãi',
            'đường Nguyễn Tri Phương',
            'đường Nguyễn Trường Tộ',
            'đường Nguyễn Văn Linh',
            'đường Nguyễn Văn Thủ',
            'đường Nguyễn Văn Tố',
            'đường Nguyễn Văn Trỗi',
            'đường Nguyễn Xuân Nhĩ',
            'đường Nguyễn Xuân Ôn',
            'đường Như Nguyệt',
            'đường Nơ Trang Lơng',
            'đường Núi Thành',
            'đường Ông Ích Khiêm',
            'đường Pasteur',
            'đường Phạm Hồng Thái',
            'đường Phạm Ngọc Thạch',
            'đường Phạm Phú Thứ',
            'đường Phạm Thế Hiển',
            'đường Phạm Văn Bạch',
            'đường Phạm Văn Nghị',
            'đường Phan Anh',
            'đường Phan Bội Châu',
            'đường Phan Châu Trinh',
            'đường Phan Đăng Lưu',
            'đường Phan Đình Phùng',
            'đường Phan Huy Ôn',
            'đường Phan Kế Bính',
            'đường Phan Thành Tài',
            'đường Quang Trung',
            'đường Quy Mỹ',
            'đường Tạ Hiện',
            'đường Tăng Bạt Hổ',
            'đường Thái Phiên',
            'đường Thân Cảnh Phúc',
            'đường Thăng Long',
            'đường Thành Điện Hải',
            'đường Thanh Duyên',
            'đường Thanh Hải',
            'đường Thanh Long',
            'đường Thanh Sơn',
            'đường Thanh Thủy',
            'đường Thi Sách',
            'đường Thuận Yến',
            'đường Tiên Sơn',
            'đường Tiểu La',
            'đường Tố Hữu',
            'đường Tống Phước Phổ',
            'đường Trần Bình Trọng',
            'đường Trần Can',
            'đường Trần Cừ',
            'đường Trần Đăng Ninh',
            'đường Trần Hữu Trang',
            'đường Trần Kế Xương',
            'đường Trần Phú',
            'đường Trần Quốc Toản',
            'đường Trần Quý Cáp',
            'đường Trần Tấn Mới',
            'đường Trần Thị Lý',
            'đường Trần Văn Giáp',
            'đường Trần Xuân Lê',
            'đường Triệu Nữ Vương',
            'đường Trịnh Công Sơn',
            'đường Trưng Nhị',
            'đường Trưng Nữ Vương',
            'đường Trương Chí Cương',
            'đường Trường Chinh',
            'đường Tuệ Tĩnh',
            'đường Văn Cận',
            'đường Võ Thị Sáu',
            'đường Vũ Duy Thanh',
            'đường Vũ Hữu',
            'đường Vũ Trọng Phụng',
            'đường Xuân Diệu',
            'đường Xuân Tâm',
            'đường Ỷ Lan Nguyên Phi',
            'đường Yên Bái',
        ],
    },
    {
        district: 'Quận Liên Chiểu',
        wards: [
            'phường Hòa Hiệp Bắc',
            'phường Hòa Hiệp Nam',
            'phường Hòa Khánh Bắc',
            'phường Hòa Khánh Nam',
            'phường Hòa Minh',
        ],
        streets: [
            'đường Âu Cơ',
            'đường Bắc Sơn',
            'đường Bạch Thái Bưởi',
            'đường Bùi Chát',
            'đường Bùi Hiển',
            'đường Chúc Động',
            'đường Đà Sơn',
            'đường Đàm Quang Trung',
            'đường Đàm Văn Lễ',
            'đường Đặng Chất',
            'đường Đặng Chiêm',
            'đường Đặng Dung',
            'đường Đặng Huy Tá',
            'đường Đặng Huy Trứ',
            'đường Đặng Minh Khiêm',
            'đường Đặng Tất',
            'đường Đào Công Soạn',
            'đường Đào Doãn Địch',
            'đường Đào Nghiễm',
            'đường Đào Ngọc Chua',
            'đường Đào Nguyên Phổ',
            'đường Đào Sư Tích',
            'đường Đinh Đức Thiện',
            'đường Đỗ Năng Tế',
            'đường Đỗ Nhuận',
            'đường Đoàn Phú Tứ',
            'đường Đoàn Trần Nghiệp',
            'đường Đoàn Văn Cừ',
            'đường Đồng Kè',
            'đường Đồng Xoài',
            'đường Dũng Sĩ Thanh Khê',
            'đường Dương Cát Lợi',
            'đường Dương Đức Hiền',
            'đường Hà Hồi',
            'đường Hà Văn Tính',
            'đường Hồ Bá Ôn',
            'đường Hồ Quý Ly',
            'đường Hồ Sĩ Đống',
            'đường Hồ Tùng Mậu',
            'đường Hoàng Minh Thảo',
            'đường Hoàng Tăng Bí',
            'đường Hoàng Thị Loan',
            'đường Hoàng Trung Thông',
            'đường Hoàng Văn Thái',
            'đường Hồng Thái',
            'đường Huỳnh Dạng',
            'đường Huỳnh Thị Bảo Hòa',
            'đường Kiều Oánh Mậu',
            'đường Kinh Dương Vương',
            'đường Lạc Long Quân',
            'đường Lâm Quang Thự',
            'đường Lê A',
            'đường Lê Công Kiều',
            'đường Lê Doãn Nhạ',
            'đường Lê Hiến Mai',
            'đường Lê Sao',
            'đường Lê Thạch',
            'đường Lê Thiệt',
            'đường Lê Thương',
            'đường Lê Trọng Tấn',
            'đường Lê Tự Nhất Thống',
            'đường Lê Văn Miến',
            'đường Lê Văn Sĩ',
            'đường Lê Văn Thịnh',
            'đường Lương Khánh Thiện',
            'đường Lương Trúc Đàm',
            'đường Lý Chính Thắng',
            'đường Lý Thái Tông',
            'đường Mai Văn Ngọc',
            'đường Mê Linh',
            'đường Mẹ Suốt',
            'đường Nam Cao',
            'đường Nam Trân',
            'đường Ngô Chân Lưu',
            'đường Ngô Đức Kế',
            'đường Ngô Sĩ Liên',
            'đường Ngô Thì Nhậm',
            'đường Ngô Tử Hạ',
            'đường Ngô Văn Sở',
            'đường Ngô Xuân Thu',
            'đường Ngọc Hồi',
            'đường Nguyễn An Ninh',
            'đường Nguyễn Bá Phát',
            'đường Nguyễn Bính',
            'đường Nguyễn Cảnh Chân',
            'đường Nguyễn Cảnh Dị',
            'đường Nguyễn Chánh',
            'đường Nguyễn Chích',
            'đường Nguyễn Chu Sĩ',
            'đường Nguyễn Công Triều',
            'đường Nguyễn Đình Trọng',
            'đường Nguyễn Đình Tứ',
            'đường Nguyễn Đỗ Cung',
            'đường Nguyễn Hàng Chi',
            'đường Nguyễn Huy Tưởng',
            'đường Nguyễn Khắc Nhu',
            'đường Nguyễn Khuyến',
            'đường Nguyễn Kiều',
            'đường Nguyễn Lương Bằng',
            'đường Nguyễn Mậu Kiến',
            'đường Nguyễn Minh Chấn',
            'đường Nguyễn Minh Không',
            'đường Nguyễn Mộng Tuân',
            'đường Nguyễn Như Hạnh',
            'đường Nguyễn Nhược Pháp',
            'đường Nguyễn Phước Chu',
            'đường Nguyễn Quyền',
            'đường Nguyễn Sinh Sắc',
            'đường Nguyễn Tất Thành',
            'đường Nguyễn Thái Bình',
            'đường Nguyễn Thị Cận',
            'đường Nguyễn Thị Thập',
            'đường Nguyễn Thúy',
            'đường Nguyễn Tường Phổ',
            'đường Nguyễn Văn Cừ',
            'đường Nguyễn Viết Xuân',
            'đường Nguyễn Xí',
            'đường Ninh Tốn',
            'đường Phạm Đình Hổ',
            'đường Phạm Như Xương',
            'đường Phạm Thị Lam Anh',
            'đường Phạm Văn Ngôn',
            'đường Phạm Văn Tráng',
            'đường Phan Đình Giót',
            'đường Phan Nhu',
            'đường Phan Thị Nể',
            'đường Phan Văn Đạt',
            'đường Phan Văn Định',
            'đường Phan Văn Thuật',
            'đường Phan Văn Trường',
            'đường Phùng Chí Kiên',
            'đường Phùng Hưng',
            'đường Quách Xân',
            'đường Sử Hy Nhan',
            'đường Suối Lương',
            'đường Tạ Quang Bửu',
            'đường Tân Trào',
            'đường Thân Công Tài',
            'đường Thanh Nghị',
            'đường Thanh Tịnh',
            'đường Thích Quảng Đức',
            'đường Tô Hiệu',
            'đường Tôn Đức Thắng',
            'đường Tống Duy Tân',
            'đường Tốt Động',
            'đường Trần Anh Tông',
            'đường Trần Bích San',
            'đường Trần Đăng',
            'đường Trần Đình Nam',
            'đường Trần Đình Tri',
            'đường Trần Đức',
            'đường Trần Minh Tông',
            'đường Trần Nguyên Đán',
            'đường Trần Quang Long',
            'đường Trần Quý Khoách',
            'đường Trần Tấn',
            'đường Trần Triệu Luật',
            'đường Trần Văn Kỷ',
            'đường Trịnh Khắc Lập',
            'đường Trương Công Huấn',
            'đường Trương Văn Đa',
            'đường Trương Vân Lĩnh',
            'đường Tự Đức',
            'đường Tú Quỳ',
            'đường Võ Duy Dương',
            'đường Vũ Huy Tấn',
            'đường Vũ Lập',
            'đường Vũ Ngọc Phan',
        ],
    },
    {
        district: 'Quận Ngũ Hành Sơn',
        wards: [
            'phường Hòa Hải',
            'phường Hòa Quý',
            'phường Khuê Mỹ',
            'phường Mỹ An',
        ],
        streets: [
            'đường An Dương Vương',
            'đường An Nông',
            'đường An Tư Công Chúa',
            'đường Anh Thơ',
            'đường Ấp Bắc',
            'đường Bà Bang Nhãn',
            'đường Bà Huyện Thanh Quan',
            'đường Bát Nàn Công Chúa',
            'đường Bình Giã',
            'đường Bình Kỳ',
            'đường Bùi Bỉnh Uyên',
            'đường Bùi Quốc Khái',
            'đường Bùi Tá Hân',
            'đường Bùi Thế Mỹ',
            'đường Cao Hồng Lãnh',
            'đường Châu Thị Vĩnh Tế',
            'đường Chế Lan Viên',
            'đường Chu Cẩm Phong',
            'đường Chu Lai',
            'đường Chương Dương',
            'đường Đặng Đoàn Bằng',
            'đường Đặng Thái Thân',
            'đường Đặng Văn Bá',
            'đường Đặng Xuân Thiều',
            'đường Đào Duy Tùng',
            'đường Đinh Gia Khánh',
            'đường Đỗ Bá',
            'đường Đỗ Bí',
            'đường Doãn Kế Thiện',
            'đường Đoàn Khuê',
            'đường Doãn Uẩn',
            'đường Đồng Phước Huyền',
            'đường Dương Bạch Mai',
            'đường Dương Khuê',
            'đường Dương Thị Xuân Quý',
            'đường Dương Tôn Hải',
            'đường Dương Tử Giang',
            'đường Dương Tụ Quán',
            'đường Hải Triều',
            'đường Hàm Tử',
            'đường Hằng Phương Nữ Sĩ',
            'đường Hồ Huân Nghiệp',
            'đường Hồ Nghinh',
            'đường Hồ Xuân Hương',
            'đường Hóa Mỹ',
            'đường Hoài Thanh',
            'đường Hoàng Bật Đạt',
            'đường Hoàng Bình Chính',
            'đường Hoàng Công Chất',
            'đường Hoàng Hối Khanh',
            'đường Hoàng Kế Viêm',
            'đường Hoàng Thiều Hoa',
            'đường Hoàng Trọng Mậu',
            'đường Hoàng Văn Hòe',
            'đường Hoàng Văn Lai',
            'đường Huyền Trân Công Chúa',
            'đường Huỳnh Bá Chánh',
            'đường Huỳnh Lắm',
            'đường Huỳnh Thị Một',
            'đường Huỳnh Văn Nghệ',
            'đường Khuê Đông',
            'đường Kim Đồng',
            'đường Lã Xuân Oai',
            'đường Lê Đình Chinh',
            'đường Lê Hữu Khánh',
            'đường Lê Hy Cát',
            'đường Lê Lộ',
            'đường Lê Như Hổ',
            'đường Lê Quang Đạo',
            'đường Lê Quát',
            'đường Lê Thành Phương',
            'đường Lê Thì Hiến',
            'đường Lê Thị Riêng',
            'đường Lê Thiện Trị',
            'đường Lê Trí Viễn',
            'đường Lê Trọng Thứ',
            'đường Lê Trung Đình',
            'đường Lê Văn Hiến',
            'đường Lê Văn Hưu',
            'đường Lê Văn Tâm',
            'đường Lê Văn Thủ',
            'đường Lộc Ninh',
            'đường Lương Đắc Bằng',
            'đường Lương Thúc Kỳ',
            'đường Lưu Đình Chất',
            'đường Lưu Quang Thuận',
            'đường Lưu Quang Vũ',
            'đường Lưu Văn Lang',
            'đường Lý Văn Phức',
            'đường Mạc Cửu',
            'đường Mạc Thiên Tích',
            'đường Mai Đăng Chơn',
            'đường Mai Thúc Lân',
            'đường Minh Mạng',
            'đường Mỹ An',
            'đường Nam Kỳ Khởi Nghĩa',
            'đường Nghiêm Xuân Yêm',
            'đường Ngô Thì Sĩ',
            'đường Ngô Viết Hữu',
            'đường Ngũ Hành Sơn',
            'đường Nguyễn Bá Lân',
            'đường Nguyễn Bá Ngọc',
            'đường Nguyễn Cơ Thạch',
            'đường Nguyễn Cửu Vân',
            'đường Nguyễn Đình Chiểu',
            'đường Nguyễn Đình Hiến',
            'đường Nguyễn Đình Trân',
            'đường Nguyễn Dục',
            'đường Nguyễn Đức Thuận',
            'đường Nguyễn Duy Cung',
            'đường Nguyễn Duy Trinh',
            'đường Nguyễn Hữu Cầu',
            'đường Nguyễn Hữu Hào',
            'đường Nguyễn Khắc Viện',
            'đường Nguyễn Lữ',
            'đường Nguyễn Minh Châu',
            'đường Nguyễn Nghiễm',
            'đường Nguyễn Phạm Tuân',
            'đường Nguyễn Phan Chánh',
            'đường Nguyễn Phước Lan',
            'đường Nguyễn Quang Lâm',
            'đường Nguyễn Quốc Trị',
            'đường Nguyễn Quý Anh',
            'đường Nguyễn Quý Cảnh',
            'đường Nguyễn Tạo',
            'đường Nguyễn Thần Hiến',
            'đường Nguyễn Thế Kỷ',
            'đường Nguyễn Thức Đường',
            'đường Nguyễn Thức Tự',
            'đường Nguyễn Trọng Hợp',
            'đường Nguyễn Tư Giản',
            'đường Nguyễn Tuyển',
            'đường Nguyễn Văn Hưởng',
            'đường Nguyễn Văn Nguyễn',
            'đường Nguyễn Văn Thoại',
            'đường Nguyễn Xiển',
            'đường Non Nước',
            'đường Phạm Đức Nam',
            'đường Phạm Hữu Kính',
            'đường Phạm Hữu Nhật',
            'đường Phạm Khiêm Ích',
            'đường Phạm Kiệt',
            'đường Phạm Như Hiền',
            'đường Phạm Nổi',
            'đường Phạm Thận Duật',
            'đường Phạm Tuấn Tài',
            'đường Phan Đình Thông',
            'đường Phan Đình Trọng',
            'đường Phan Hành Sơn',
            'đường Phan Liêm',
            'đường Phan Thúc Duyện',
            'đường Phan Tôn',
            'đường Phan Tòng',
            'đường Phan Tứ',
            'đường Quảng Nam',
            'đường Song Hào',
            'đường Sư Vạn Hạnh',
            'đường Tân Lưu',
            'đường Tân Trà',
            'đường Tây Sơn',
            'đường Thái Văn A',
            'đường Thép Mới',
            'đường Thích Phước Huệ',
            'đường Thượng Đức',
            'đường Tiên Sơn',
            'đường Tôn Thất Thiệp',
            'đường Trà Lộ',
            'đường Trần Đại Nghĩa',
            'đường Trần Hoành',
            'đường Trần Hữu Độ',
            'đường Trần Hữu Dực',
            'đường Trần Khánh Dư',
            'đường Trần Minh Thiệt',
            'đường Trần Quốc Hoàn',
            'đường Trần Quốc Vượng',
            'đường Trần Thị Lý',
            'đường Trần Trọng Khiêm',
            'đường Trần Văn Đán',
            'đường Trần Văn Dư',
            'đường Trần Văn Giảng',
            'đường Trần Văn Hai',
            'đường Trần Văn Thành',
            'đường Trần Xuân Hòa',
            'đường Trịnh Lỗi',
            'đường Trương Công Hy',
            'đường Trương Đăng Quế',
            'đường Trương Gia Mô',
            'đường Trương Minh Giảng',
            'đường Trương Minh Hùng',
            'đường Trường Sa',
            'đường Trương Văn Hiến',
            'đường Tùng Thiện Vương',
            'đường Tuy Lý Vương',
            'đường Ung Văn Khiêm',
            'đường Vân Đài Nữ Sĩ',
            'đường Văn Tân',
            'đường Vạn Tường',
            'đường Việt Bắc',
            'đường Võ Chí Công',
            'đường Võ Nguyên Giáp',
            'đường Võ Như Hưng',
            'đường Võ Văn Đặng',
            'đường Võ Văn Đồng',
            'đường Võ Quý Huân',
            'đường Vũ Duy Đoán',
            'đường Vũ Hữu Lợi',
            'đường Vũ Mộng Nguyên',
            'đường Vũ Văn Cẩn',
            'đường Xóm Đồng',
            'đường Yersin',
        ],
    },
    {
        district: 'Quận Sơn Trà',
        wards: [
            'phường An Hải Bắc',
            'phường An Hải Đông',
            'phường An Hải Tây',
            'phường Mân Thái',
            'phường Nại Hiên Đông',
            'phường Phước Mỹ',
            'phường Thọ Quang',
        ],
        streets: [
            'đường An Đồn',
            'đường An Hải Bắc',
            'đường An Mỹ',
            'đường An Vĩnh',
            'đường Bình Than',
            'đường Bùi Dương Lịch',
            'đường Bùi Hữu Nghĩa',
            'đường Bùi Huy Bích',
            'đường Bùi Lâm',
            'đường Bùi Quốc Hưng',
            'đường Bùi Thị Xuân',
            'đường Cao Bá Nhạ',
            'đường Cao Bá Quát',
            'đường Cao Lỗ',
            'đường Chính Hữu',
            'đường Chu Huy Mân',
            'đường Dã Tượng',
            'đường Đặng Nhữ Lâm',
            'đường Đặng Trần Côn',
            'đường Đặng Vũ Hỷ',
            'đường Đào Duy Kỳ',
            'đường Đinh Công Trứ',
            'đường Đinh Đạt',
            'đường Đinh Lễ',
            'đường Đinh Nhật Thận',
            'đường Đinh Thị Hòa',
            'đường Đỗ Anh Hàn',
            'đường Đỗ Hành',
            'đường Đỗ Huy Uyển',
            'đường Đỗ Thế Chấp',
            'đường Đỗ Xuân Hợp',
            'đường Đông Du',
            'đường Đông Giang',
            'đường Đông Kinh Nghĩa Thục',
            'đường Dương Đình Nghệ',
            'đường Dương Lâm',
            'đường Dương Thạc',
            'đường Dương Thanh',
            'đường Dương Trí Trạch',
            'đường Dương Tự Minh',
            'đường Dương Văn An',
            'đường Dương Vân Nga',
            'đường Giáp Hải',
            'đường Hà Bổng',
            'đường Hà Chương',
            'đường Hà Đặc',
            'đường Hà Kỳ Ngộ',
            'đường Hà Thị Thân',
            'đường Hà Tông Huân',
            'đường Hồ Hán Thương',
            'đường Hồ Học Lãm',
            'đường Hồ Nghinh',
            'đường Hồ Sĩ Phấn',
            'đường Hồ Sĩ Tân',
            'đường Hồ Thấu',
            'đường Hoa Lư',
            'đường Hoàng Đức Lương',
            'đường Hoàng Quốc Việt',
            'đường Hoàng Sa',
            'đường Hoàng Sĩ Khải',
            'đường Hoàng Việt',
            'đường Hương Hải Thiền Sư',
            'đường Huy Du',
            'đường Huyền Quang',
            'đường Khúc Hạo',
            'đường Khúc Thừa Dụ',
            'đường Lâm Hoành',
            'đường Lê Bình',
            'đường Lê Bôi',
            'đường Lê Cảnh Tuân',
            'đường Lê Chân',
            'đường Lê Đức Thọ',
            'đường Lê Hữu Kiều',
            'đường Lê Hữu Trác',
            'đường Lê Lâm',
            'đường Lê Mạnh Trinh',
            'đường Lê Ninh',
            'đường Lê Phụ Trần',
            'đường Lê Phụng Hiểu',
            'đường Lê Tấn Toán',
            'đường Lê Tấn Trung',
            'đường Lê Thước',
            'đường Lê Văn Duyệt',
            'đường Lê Văn Huân',
            'đường Lê Văn Lương',
            'đường Lê Văn Quý',
            'đường Lê Văn Thiêm',
            'đường Lê Văn Thứ',
            'đường Loseby',
            'đường Lương Hữu Khánh',
            'đường Lương Thế Vinh',
            'đường Lưu Hữu Phước',
            'đường Lý Đạo Thành',
            'đường Lý Nam Đế',
            'đường Lý Nhật Quang',
            'đường Lý Thánh Tông',
            'đường Lý Tử Tấn',
            'đường Lý Văn Tố',
            'đường Mai Hắc Đế',
            'đường Morrison',
            'đường Ngô Cao Lãng',
            'đường Ngô Quang Huy',
            'đường Ngô Quyền',
            'đường Ngô Thì Hiệu',
            'đường Ngô Thì Hương',
            'đường Ngô Thì Sĩ',
            'đường Ngô Thì Trí',
            'đường Ngô Trí Hòa',
        ],
    },
    {
        district: 'Quận Thanh Khê',
        wards: [
            'phường An Khê',
            'phường Chính Gián',
            'phường Hòa Khê',
            'phường Tam Thuận',
            'phường Tân Chính',
            'phường Thạc Gián',
            'phường Thanh Khê Đông',
            'phường Thanh Khê Tây',
            'phường Vĩnh Trung',
            'phường Xuân Hà',
        ],
        streets: [
            'đường An Xuân',
            'đường Bàu Làng',
            'đường Bế Văn Đàn',
            'đường Cần Giuộc',
            'đường Cù Chính Lan',
            'đường Đặng Đình Vân',
            'đường Đặng Phúc Thông',
            'đường Đặng Thai Mai',
            'đường Đào Duy Anh',
            'đường Đào Duy Từ',
            'đường Điện Biên Phủ',
            'đường Đinh Núp',
            'đường Đinh Thị Vân',
            'đường Đinh Tiên Hoàng',
            'đường Đỗ Đức Dục',
            'đường Đỗ Ngọc Du',
            'đường Đỗ Quang',
            'đường Đoàn Nhữ Hài',
            'đường Dũng Sĩ Thanh Khê',
            'đường Hà Huy Tập',
            'đường Hải Phòng',
            'đường Hàm Nghi',
            'đường Hồ Quý Ly',
            'đường Hồ Tương',
            'đường Hoàng Hoa Thám',
            'đường Hoàng Thị Loan',
            'đường Hùng Vương',
            'đường Huỳnh Ngọc Huệ',
            'đường Kỳ Đồng',
            'đường Lê Đình Lý',
            'đường Lê Độ',
            'đường Lê Duẩn',
            'đường Lê Duy Đình',
            'đường Lê Lộ',
            'đường Lê Ngô Cát',
            'đường Lê Quang Sung',
            'đường Lê Thị Tính',
            'đường Lê Thị Xuyến',
            'đường Lê Trọng Tấn',
            'đường Lý Thái Tổ',
            'đường Lý Thái Tông',
            'đường Lý Triện',
            'đường Mai Xuân Thưởng',
            'đường Mẹ Hiền',
            'đường Mẹ Nhu',
            'đường Ngô Gia Khảm',
            'đường Nguyễn Biểu',
            'đường Nguyễn Cao',
            'đường Nguyễn Công Hãng',
            'đường Nguyễn Đăng',
            'đường Nguyễn Đình Tựu',
            'đường Nguyễn Đức Trung',
            'đường Nguyễn Gia Thiều',
            'đường Nguyễn Giản Thanh',
            'đường Nguyễn Hoàng',
            'đường Nguyên Hồng',
            'đường Nguyễn Hữu Thận',
            'đường Nguyễn Huy Lượng',
            'đường Nguyễn Khang',
            'đường Nguyễn Nghiêm',
            'đường Nguyễn Phi Khanh',
            'đường Nguyễn Phước Nguyên',
            'đường Nguyễn Phước Thái',
            'đường Nguyễn Tất Thành',
            'đường Nguyễn Thanh Năm',
            'đường Nguyễn Thị Bảy',
            'đường Nguyễn Thị Thập',
            'đường Nguyễn Tri Phương',
            'đường Nguyễn Văn Huề',
            'đường Nguyễn Văn Linh',
            'đường Nguyễn Văn Phương',
            'đường Ông Ích Khiêm',
            'đường Phạm Ngọc Mậu',
            'đường Phạm Nhữ Tăng',
            'đường Phạm Văn Nghị',
            'đường Phan Phu Tiên',
            'đường Phan Thanh',
            'đường Phan Xích Long',
            'đường Phục Đán',
            'đường Phùng Hưng',
            'đường Quang Dũng',
            'đường Tản Đà',
            'đường Thái Thị Bồi',
            'đường Thân Nhân Trung',
            'đường Thanh Tân',
            'đường Thúc Tề',
            'đường Tô Ngọc Vân',
            'đường Tôn Thất Đạm',
            'đường Tôn Thất Tùng',
            'đường Trần Cao Vân',
            'đường Trần Thái Tông',
            'đường Trần Thanh Trung',
            'đường Trấn Tống',
            'đường Trần Xuân Lê',
            'đường Trường Chinh',
            'đường Văn Cao',
            'đường Võ Văn Tần',
            'đường Vũ Quỳnh',
        ],
    },
    {
        district: 'Huyện Hòa Vang',
        wards: [
            'phường Hòa Phong',
            'phường Hòa Bắc',
            'phường Hòa Châu',
            'phường Hòa Khương',
            'phường Hòa Liên',
            'phường Hòa Nhơn',
            'phường Hòa Ninh',
            'phường Hòa Phú',
            'phường Hòa Phước',
            'phường Hòa Sơn',
            'phường Hòa Tiến',
        ],
        streets: [
            'đường Âu Dương Lân',
            'đường Bùi Cẩm Hổ',
            'đường Bùi Huy Đáp',
            'đường Cao Bá Đạt',
            'đường Cồn Đỉnh',
            'đường Đặng Đức Siêu',
            'đường Đặng Hòa',
            'đường Đặng Văn Kiều',
            'đường Đào Trinh Nhất',
            'đường Đinh Văn Chất',
            'đường Hà Duy Phiên',
            'đường Hà Văn Mao',
            'đường Hoàng Đạo Thành',
            'đường Hoàng Văn Thái',
            'đường Huỳnh Tịnh Của',
            'đường Kha Vạng Cân',
            'đường Kiều Sơn Đen',
            'đường Lê Đình Diên',
            'đường Lê Trực',
            'đường Lê Văn Hoan',
            'đường Lý Thiên Bảo',
            'đường Mai An Tiêm',
            'đường Mai Thúc Trực',
            'đường Mẹ Thứ',
            'đường Nam Kỳ Khởi Nghĩa',
            'đường Ngô Mây',
            'đường Nguyễn Án',
            'đường Nguyễn Bá Loan',
            'đường Nguyễn Bảo',
            'đường Nguyễn Hàm Ninh',
            'đường Nguyễn Hồng Ánh',
            'đường Nguyễn Huy Oánh',
            'đường Nguyễn Khả Trạc',
            'đường Nguyễn Kim',
            'đường Nguyễn Văn Tỵ',
            'đường Nguyễn Văn Vĩnh',
            'đường Nguyễn Văn Xuân',
            'đường Phạm Công Trứ',
            'đường Phạm Hùng',
            'đường Phạm Hữu Nghi',
            'đường Phan Thúc Trực',
            'đường Phan Văn Đáng',
            'đường Quảng Xương',
            'đường Tế Hanh',
            'đường Thu Bồn',
            'đường Trần Tử Bình',
            'đường Trần Văn Giàu',
            'đường Trịnh Quang Xuân',
            'đường Trung Đồng',
            'đường Trường Chinh',
            'đường Trường Sơn',
            'đường Trương Vĩnh Ký',
            'đường Võ Thành Vỹ',
            'đường Vũ Miên',
        ],
    },
    {
        district: 'Huyện Hoàng Sa',
    },
];
