const routes = {
    admin: '/quan-tri-vien/trang-chu',
    adminRegister: '/quan-tri-vien/dang-ky',
    adminLogin: '/quan-tri-vien',
    adminForgotPassword: '/quan-tri-vien/quen-mat-khau',
    adminChangePassword: '/quan-tri-vien/doi-mat-khau',
    adminProfile: '/quan-tri-vien/thong-tin-ca-nhan',
    adminDetailPost: '/quan-tri-vien/quan-ly-bai-dang/chi-tiet-bai-dang',
    adminTransaction: '/quan-tri-vien/quan-ly-giao-dich',
    adminDetailRevenue: '/quan-tri-vien/quan-ly-giao-dich/chi-tiet-giao-dich',
    membermng: '/quan-tri-vien/quan-ly-thanh-vien',
    detailMember: '/quan-tri-vien/quan-ly-thanh-vien',
    adminPostMng: '/quan-tri-vien/quan-ly-bai-dang',
    home: '/',
    motel: '/phong-tro',
    house: '/nha-nguyen-can',
    findroomates: '/tim-nguoi-o-ghep',
    office: '/van-phong',
    apartment: '/chung-cu-can-ho',
    ground: '/mat-bang',
    search: '/search',
    profile: '/thong-tin-ca-nhan',
    password: '/doi-mat-khau',
    postmng: '/quan-ly-bai-dang',
    post: '/quan-ly-bai-dang/dang-tin',
    postlist: '/quan-ly-bai-dang/danh-sach-tin-dang',
    transaction: '/lich-su-giao-dich',
    login: '/dang-nhap',
    register: '/dang-ky',
    detailPage: '/chi-tiet-bai-dang',
    searchResult: '/ket-qua-tim-kiem',
    message: '/tat-ca-tin-nhan',
    postListOfUser: '/tat-ca-tin-dang-ca-nhan',
    forgotPassword: '/quen-mat-khau',
    payment: '/nap-tien',
};

export default routes;
